--CONECTAR COMO system/oracle@dw as sysdba
connect sys/oralce_4U@dw as sysdba
--crea directorios y da permisos a dw
--CREATE OR REPLACE DIRECTORY DIR_DW AS 'C:\DW\';
CREATE OR REPLACE DIRECTORY DIR_DW AS 'C:\Users\Taller\Desktop\ETL\';
--damos privilegios sobre los directorios a dw de r-w
GRANT READ ON DIRECTORY DIR_DW TO dw;
GRANT WRITE ON DIRECTORY DIR_DW TO dw

--CONECTAR COMO dw/dw@dw
connect dw/dw@dw
--en caso de que ya exista
--drop TABLE "EXT_EMPLOYEES_DIM"

CREATE TABLE "EXT_EMPLOYEES_DIM"
(
 "EMPID" NUMBER(6),
 "NOMBRE" VARCHAR2(20),
 "APELLIDO" VARCHAR2(25),
 "EMAIL" VARCHAR2(25),
 "TELEFONO" VARCHAR2(20),
 "JOBID" VARCHAR2(10),
 "MGRID" NUMBER(6),
 "DEPTID" NUMBER(4),
 "DEPARTMENTNAME" VARCHAR2(30)
)
ORGANIZATION external
(
  TYPE oracle_loader
  DEFAULT DIRECTORY DIR_DW
  ACCESS PARAMETERS
  (
   RECORDS DELIMITED BY NEWLINE CHARACTERSET WE8MSWIN1252
   BADFILE 'refresco_employees.bad'
   LOGFILE 'REFRESCO_EMPLOYEES_DIM.log'
   READSIZE 1048576
   FIELDS TERMINATED BY "," OPTIONALLY ENCLOSED BY '"' LDRTRIM
   REJECT ROWS WITH ALL NULL FIELDS
  (
    "EMPID" CHAR(255)
    TERMINATED BY "," OPTIONALLY ENCLOSED BY '"',
    "NOMBRE" CHAR(255)
    TERMINATED BY "," OPTIONALLY ENCLOSED BY '"',
    "APELLIDO" CHAR(255)
    TERMINATED BY "," OPTIONALLY ENCLOSED BY '"',
    "EMAIL" CHAR(255)
    TERMINATED BY "," OPTIONALLY ENCLOSED BY '"',
    "TELEFONO" CHAR(255)
    TERMINATED BY "," OPTIONALLY ENCLOSED BY '"',
    "JOBID" CHAR(255)
    TERMINATED BY "," OPTIONALLY ENCLOSED BY '"',
    "MGRID" CHAR(255)
    TERMINATED BY "," OPTIONALLY ENCLOSED BY '"',
    "DEPTID" CHAR(255)
    TERMINATED BY "," OPTIONALLY ENCLOSED BY '"',
    "DEPARTMENTNAME" CHAR(255)
    TERMINATED BY "," OPTIONALLY ENCLOSED BY '"'
  )
)
location
(
 'refresco_employees.txt'
)
)REJECT LIMIT UNLIMITED
